### ISSUE TITLE
addlang command not executing.

### ISSUE THREAD

**Issue by devjmc** [Liga-dos-Programadores/Project-A#23]
Thanks for the project. Using it as reference to build another bot. But why not in English? (myself is Spanish though)

Some commands seem not working (e.g. addlang). 
Although after npm start, the console shows that the module has loaded, a simple console.log inside the command does not show the command being executed. However the help command does. Why is that?

What are the plans for the future of this project?

**Comment by devjmc** [comment]
OK, found it. See message.js. The command is skipped if the conf.onlyguilds is true, which is the case for the addling command.

**Comment by beescuit** [comment]
Hi! I only noticed this issue today because of github's webhooks in the discord channel as you had closed it and it didn't pop up at my notification tab here in github. Just answering your question, the project is entirely in Portuguese because it's meant to be specific for our Programming server (which is Brazillian) so there's no good reason for translating it.
Also, I've fixed some bugs in the project since this issue, so I think it would be cool for you to check it out if you want.
